# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft/NeoForge versions
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.86
neo_version_range=[21.1,)
loader_version_range=[4,)

# Parchment mappings (optional, for better parameter names)
parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28

# Mod properties
mod_id=alexsmobs
mod_name=Alex's Mobs
mod_license=GNU Lesser General Public License
mod_version=1.22.9
mod_authors=Alexthe668, Carro1001, Paint_Ninja
mod_description=New, original, engaging, and aesthetic mobs for Minecraft.

# JEI (for 1.21.1)
jei_version=19.21.0.247
